version: '3.7'

services:

  db:
    container_name: ContainerPostgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: andres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    networks:
      - nuevaRed

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test
      SPRING_DATASOURCE_USERNAME: andres
      SPRING_DATASOURCE_PASSWORD: root
      NAME: ContainerPostgres
    networks:
      - nuevaRed

networks:
  nuevaRed:
    driver: bridge